# TCL File Generated by Component Editor 17.0
# Wed Jan 13 00:09:30 COT 2021
# DO NOT MODIFY


# 
# slam "slam" v1.0
#  2021.01.13.00:09:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module slam
# 
set_module_property DESCRIPTION ""
set_module_property NAME slam
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP other
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME slam
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL slam_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file slam_avalon.vhd VHDL PATH "../slam_avalon - v3/slam_avalon.vhd" TOP_LEVEL_FILE
add_fileset_file abs_diff.vhd VHDL PATH "../slam_avalon - v3/abs_diff.vhd"
add_fileset_file alt_add_sub.vhd VHDL PATH "../slam_avalon - v3/alt_add_sub.vhd"
add_fileset_file alt_float2int_convert.vhd VHDL PATH "../slam_avalon - v3/alt_float2int_convert.vhd"
add_fileset_file alt_float_comp.vhd VHDL PATH "../slam_avalon - v3/alt_float_comp.vhd"
add_fileset_file alt_float_div.cmp OTHER PATH "../slam_avalon - v3/alt_float_div.cmp"
add_fileset_file alt_float_div.hex HEX PATH "../slam_avalon - v3/alt_float_div.hex"
add_fileset_file alt_float_div.vhd VHDL PATH "../slam_avalon - v3/alt_float_div.vhd"
add_fileset_file alt_float_mult.vhd VHDL PATH "../slam_avalon - v3/alt_float_mult.vhd"
add_fileset_file alt_int2float_convert.vhd VHDL PATH "../slam_avalon - v3/alt_int2float_convert.vhd"
add_fileset_file alt_int_divisor.vhd VHDL PATH "../slam_avalon - v3/alt_int_divisor.vhd"
add_fileset_file coord_transform.vhd VHDL PATH "../slam_avalon - v3/coord_transform.vhd"
add_fileset_file float2int.vhd VHDL PATH "../slam_avalon - v3/float2int.vhd"
add_fileset_file float_abs.vhd VHDL PATH "../slam_avalon - v3/float_abs.vhd"
add_fileset_file float_add_sub.vhd VHDL PATH "../slam_avalon - v3/float_add_sub.vhd"
add_fileset_file float_comparator.vhd VHDL PATH "../slam_avalon - v3/float_comparator.vhd"
add_fileset_file float_divisor.vhd VHDL PATH "../slam_avalon - v3/float_divisor.vhd"
add_fileset_file float_multiplier.vhd VHDL PATH "../slam_avalon - v3/float_multiplier.vhd"
add_fileset_file int2float.vhd VHDL PATH "../slam_avalon - v3/int2float.vhd"
add_fileset_file int_adder.vhd VHDL PATH "../slam_avalon - v3/int_adder.vhd"
add_fileset_file int_res.vhd VHDL PATH "../slam_avalon - v3/int_res.vhd"
add_fileset_file ip_ram.qip OTHER PATH "../slam_avalon - v3/ip_ram.qip"
add_fileset_file ip_ram.vhd VHDL PATH "../slam_avalon - v3/ip_ram.vhd"
add_fileset_file map_handler.vhd VHDL PATH "../slam_avalon - v3/map_handler.vhd"
add_fileset_file map_handler_fsm.vhd VHDL PATH "../slam_avalon - v3/map_handler_fsm.vhd"
add_fileset_file map_init_fsm.vhd VHDL PATH "../slam_avalon - v3/map_init_fsm.vhd"
add_fileset_file map_neighbour_detector.vhd VHDL PATH "../slam_avalon - v3/map_neighbour_detector.vhd"
add_fileset_file map_transform_fsm.vhd VHDL PATH "../slam_avalon - v3/map_transform_fsm.vhd"
add_fileset_file map_update_fsm.vhd VHDL PATH "../slam_avalon - v3/map_update_fsm.vhd"
add_fileset_file my_package.vhd VHDL PATH "../slam_avalon - v3/my_package.vhd"
add_fileset_file my_register.vhd VHDL PATH "../slam_avalon - v3/my_register.vhd"
add_fileset_file my_register_unsigned.vhd VHDL PATH "../slam_avalon - v3/my_register_unsigned.vhd"
add_fileset_file nBitcomparator.vhd VHDL PATH "../slam_avalon - v3/nBitcomparator.vhd"
add_fileset_file neighbour_detector.vhd VHDL PATH "../slam_avalon - v3/neighbour_detector.vhd"
add_fileset_file quadrant_scatter.vhd VHDL PATH "../slam_avalon - v3/quadrant_scatter.vhd"
add_fileset_file quadrant_selector.vhd VHDL PATH "../slam_avalon - v3/quadrant_selector.vhd"
add_fileset_file quadrant_selector_logic.vhd VHDL PATH "../slam_avalon - v3/quadrant_selector_logic.vhd"
add_fileset_file quadrant_to_map_fsm.vhd VHDL PATH "../slam_avalon - v3/quadrant_to_map_fsm.vhd"
add_fileset_file scale_convert2float.vhd VHDL PATH "../slam_avalon - v3/scale_convert2float.vhd"
add_fileset_file scale_convert2int.vhd VHDL PATH "../slam_avalon - v3/scale_convert2int.vhd"
add_fileset_file scatter_control_fsm.vhd VHDL PATH "../slam_avalon - v3/scatter_control_fsm.vhd"
add_fileset_file slam.vhd VHDL PATH "../slam_avalon - v3/slam.vhd"
add_fileset_file tiny_counter.vhd VHDL PATH "../slam_avalon - v3/tiny_counter.vhd"
add_fileset_file univ_bin_counter.vhd VHDL PATH "../slam_avalon - v3/univ_bin_counter.vhd"
add_fileset_file voxel_filter.vhd VHDL PATH "../slam_avalon - v3/voxel_filter.vhd"
add_fileset_file voxel_fsm.vhd VHDL PATH "../slam_avalon - v3/voxel_fsm.vhd"
add_fileset_file voxel_quadrant.vhd VHDL PATH "../slam_avalon - v3/voxel_quadrant.vhd"
add_fileset_file voxel_ready_fsm.vhd VHDL PATH "../slam_avalon - v3/voxel_ready_fsm.vhd"


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 s_address address Input 15
add_interface_port avalon_slave_0 s_chipselect chipselect Input 1
add_interface_port avalon_slave_0 s_write write Input 1
add_interface_port avalon_slave_0 s_writedata writedata Input 128
add_interface_port avalon_slave_0 s_readdata readdata Output 128
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end s_q led Output 1
add_interface_port conduit_end s_v led1 Output 1
add_interface_port conduit_end q_h led2 Output 2
add_interface_port conduit_end s_irq led4 Output 1
add_interface_port conduit_end hps led3 Output 1

